
name: Deploy BankFlow API to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3C01587E4EC040CA9467D1863A916848 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_10E3E83C4F594AF49ECEBA647DD2B5C1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E0F6E29BE6343589532CFBE74F0C84D }}

      - name: Deploy BankFlow API
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bankflow-api-2026'
          slot-name: 'Production'
          package: .

